import { Logger } from "../logger/Logger";
import { ColumnData, ExcelStruct } from "../parser/ExcelParser";
import { DataType } from "../parser/ParserEnum";
import fs from "fs";
import { pathToNormal, toUpperCamelCase } from "../utils/StringUtils";
import { ParseJsonFunc } from "../parser/JsonParser";

const HEAD_ROW_COUNT = 5;     // 表头行数

class JsonKeyValue {
    key: string = "";
    valueType : string = "";
    children: Map<string, JsonKeyValue> = new Map();
}


export function exportCsClass(excelStruct: ExcelStruct, outPath:string) {
    if (excelStruct == null) {
        Logger.error(`exportTsClass error, excelStruct is null`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsClass error, outPath is error: ${outPath}`);
        return;
    }

    const columnDataList = excelStruct.columnDataList;
    if (columnDataList == null || columnDataList.length == 0) {
        Logger.error(`exportTsClass error, columnDataList is null or empty`);
        return;
    }

    const content = generateCsClass(excelStruct);
    let className = excelStruct.configName;
    className = toUpperCamelCase(className);
    outPath = pathToNormal(outPath);
    let newOutPath = outPath.substring(0, outPath.lastIndexOf("/")) + "/" + className + ".cs";
    fs.writeFileSync(newOutPath, content);
}

function generateCsClass(excelStruct: ExcelStruct): string {
    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n`;

    // 类名
    let className = excelStruct.configName;
    // 去除 空格,-,_字符, 并且这些字符后的字母大写
    className = toUpperCamelCase(className);
    className = className.substring(0, 1).toUpperCase() + className.substring(1);
    
    let typeName = className + "Config";
    className += "Class";

    // 命名空间
    let namespace = "FreeParticle.ExcelConfig";
    content += `using System;\n`;
    content += `using System.Collections;\n`;
    content += `using System.Collections.Generic;\n`;
    content += `using Newtonsoft.Json;\n`;
    content += `using UnityEngine;\n\n`;

    content += `namespace ${namespace} {\n\n`;


    const jsonStructMap: Map<string, { content: string, interfaceName: string }> = new Map();
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        if (columnData.dataType == DataType.Json) {
            const jsonStruct = getJsonTypeStruct(excelStruct, columnData);
            jsonStructMap.set(columnData.fieldName, jsonStruct);
        }
    }

    jsonStructMap.forEach((jsonStruct, key) => {
        content += jsonStruct.content + "\n";
    });

    if (excelStruct.subKeyColumn === -1) {
        // 没有子健列
        content += `    public static class ${typeName}\n`;
        content += `    {\n`;
        content += `        public static Dictionary<${getKeyType(excelStruct)}, ${className}> Deserialize(string json) {\n`;
        content += `            var result = JsonConvert.DeserializeObject<Dictionary<${getKeyType(excelStruct)}, ${className}>>(json);\n`;
        content += `            return result;\n`;
        content += `        }\n`;
        content += `    }\n\n`;
    }
    else {
        // 有子健列
        content += `    public static class ${typeName} {\n`;
        content += `        public static Dictionary<${getKeyType(excelStruct)}, Dictionary<${getSubKeyType(excelStruct)}, ${className}>> Deserialize(string json) {\n`;
        content += `            var result = JsonConvert.DeserializeObject<Dictionary<${getKeyType(excelStruct)}, Dictionary<${getSubKeyType(excelStruct)}, ${className}>>>(json);\n`;
        content += `            return result;\n`;
        content += `        }\n`;
        content += `    }\n\n`;
    }

    content += `    [Serializable]\n`;
    content += `    public class ${className} {\n`;
 // 字段
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        content += `        /** ${columnData.commentName} */\n`;
        content += `        [JsonProperty("${columnData.fieldName}")]\n`;
        content += `        public ${getCsType(excelStruct, columnData, jsonStructMap.get(columnData.fieldName))} ${columnData.fieldName} { get; private set; }\n\n`;
    }

    content += `    }\n`;

    content += `}\n`;

    return content;
}

function getKeyType(excelStruct: ExcelStruct): string 
{
    const mainKeyColumnData = excelStruct.columnDataList[excelStruct.mainKeyColumn];
    if (mainKeyColumnData.dataType == DataType.Int) {
        return "int";
    }
    else if (mainKeyColumnData.dataType == DataType.String) {
        return "string";
    }
    return "string"; 
}

function getSubKeyType(excelStruct: ExcelStruct): string
{
    const subKeyColumnData = excelStruct.columnDataList[excelStruct.subKeyColumn];
    if (subKeyColumnData.dataType == DataType.Int) {
        return "int";
    }
    else if (subKeyColumnData.dataType == DataType.String) {
        return "string";
    }
    return "string"; 
}

function getJsonTypeStruct(excelStruct: ExcelStruct, columnData: ColumnData): {
    content: string,
    interfaceName: string
} {
    // 定义节点结构
    const rootChildren: Map<string, JsonKeyValue> = new Map();

    Logger.currentColumnName = columnData.fieldName;
    const rowCount = excelStruct.rowCount;
    const worksheet = excelStruct.sheet!;

    // 1. 遍历所有行，收集 JSON 结构
    for (let i = HEAD_ROW_COUNT + 1, len = rowCount; i <= len; i++) {
        Logger.currentRow = i;
        const row = worksheet.getRow(i);
        try {
            let text = row.getCell(columnData.column).text;
            if (text == null || text.trim() == "") {
                text = "{}"; // 空单元格视为默认对象
            }

            const json = ParseJsonFunc(text);
            if (json == null) {
                Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}`);
                continue;
            }

            // 获取值的类型字符串
            const getJsonValueType = function (value: unknown): string {
                if (typeof value === "string") return "string";
                if (typeof value === "number") return "float"; // 默认用float，兼容性好
                if (typeof value === "boolean") return "bool";
                if (Array.isArray(value)) {
                    // 如果是数组，递归检查第一个元素来确定类型，并标记为数组
                    const innerType = value.length > 0 ? getJsonValueType(value[0]) : "object"; 
                    return innerType + "[]";
                }
                if (typeof value === "object") return "object";
                return "object";
            };

            // 递归解析并合并结构
            // currentMap: 当前层级的字段Map
            // jsonObj: 当前层级的Json对象
            const parseJsonRecursive = (currentMap: Map<string, JsonKeyValue>, jsonObj: any) => {
                if (jsonObj == null || typeof jsonObj !== "object") return;

                // 如果是数组，我们需要去解析数组里的第一个元素（假设数组内结构一致）
                if (Array.isArray(jsonObj)) {
                    if (jsonObj.length > 0 && typeof jsonObj[0] === "object") {
                        // 注意：这里我们不直接遍历数组，而是依赖父级调用时传入正确的目标对象
                        // 但在当前的逻辑流中，parseJsonRecursive 主要处理 Object 的 key。
                        // 数组的处理逻辑在调用侧（下方循环中）处理比较合适。
                        parseJsonRecursive(currentMap, jsonObj[0]);
                    }
                    return;
                }

                for (const key in jsonObj) {
                    const value = jsonObj[key];
                    let type = getJsonValueType(value);
                    
                    // 获取或创建当前key的节点
                    let node = currentMap.get(key);
                    if (!node) {
                        node = new JsonKeyValue();
                        node.key = key;
                        node.valueType = type;
                        currentMap.set(key, node);
                    }

                    // 检查是否是嵌套对象或对象数组，需要递归向下合并结构
                    if (type === "object") {
                        parseJsonRecursive(node.children, value);
                    } else if (type === "object[]" || (type.endsWith("[]") && typeof value[0] === "object")) {
                        // 如果是对象数组，修改类型标记为 "object[]"，并解析数组项
                        node.valueType = "object[]"; 
                        if (Array.isArray(value) && value.length > 0) {
                            parseJsonRecursive(node.children, value[0]);
                        }
                    } else {
                        // 基本类型，更新类型（防止之前是null或者类型变更为更通用的类型，这里简单处理）
                        node.valueType = type;
                    }
                }
            };

            parseJsonRecursive(rootChildren, json);
        }
        catch (error) {
            Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}, error: ${error}`);
        }
    }

   // 2. 生成 C# 类代码
    const rootInterfaceName = toUpperCamelCase(excelStruct.configName) + toUpperCamelCase(columnData.fieldName);
    let classDefinitions = "";

    // 递归生成类函数
    // className: 当前要生成的类名
    // children: 该类的字段结构
    // indent: 缩进空格数
    const generateClassRecursive = (className: string, children: Map<string, JsonKeyValue>, indentLevel: number): string => {
        const indent = "    ".repeat(indentLevel);
        let sb = "";
        
        sb += `${indent}[Serializable]\n`;
        sb += `${indent}public partial class ${className} {\n`;

        // 收集需要生成的子类
        const subClassesToGenerate: { name: string, children: Map<string, JsonKeyValue> }[] = [];

        for (const [key, node] of children) {
            const propertyName = key; // 保持JSON中的原始字段名
            const fieldName = toUpperCamelCase(key); // C# 属性名通常大写开头，这里如果为了匹配JSON简单起见，也可以直接用 key
            
            let cSharpType = node.valueType;
            let isNested = false;

            // 处理嵌套对象
            if (node.valueType === "object") {
                const subClassName = toUpperCamelCase(key); // 使用Key作为类名
                cSharpType = subClassName;
                subClassesToGenerate.push({ name: subClassName, children: node.children });
                isNested = true;
            } 
            // 处理对象数组
            else if (node.valueType === "object[]") {
                const subClassName = toUpperCamelCase(key); // 使用Key作为类名（单数形式最好，但在自动生成中通常直接用Key）
                // 也可以尝试去掉复数 's'，例如 items -> Item，这里暂时直接用 Key
                cSharpType = `${subClassName}[]`; // 或者 List<SubClassName>
                subClassesToGenerate.push({ name: subClassName, children: node.children });
                isNested = true;
            }

            sb += `${indent}    [JsonProperty("${propertyName}")]\n`;
            // 注意：这里属性名用了 key，如果需要大写开头，可以改为 public ${cSharpType} ${toUpperCamelCase(key)} { get; private set; }
            sb += `${indent}    public ${cSharpType} ${key} { get; private set; }\n\n`;
        }

        // 在类内部（或者外部，这里选择内部以保持命名空间整洁）生成子类
        for (const sub of subClassesToGenerate) {
            sb += generateClassRecursive(sub.name, sub.children, indentLevel + 1);
            sb += "\n";
        }

        sb += `${indent}}\n`;
        return sb;
    };

    if (rootChildren.size > 0) {
        classDefinitions = generateClassRecursive(rootInterfaceName, rootChildren, 1);
    } else {
        // 如果没有解析到任何字段，生成一个空类
        classDefinitions = `    [Serializable]\n    public partial class ${rootInterfaceName} {}\n`;
    }

    return {
        content: classDefinitions,
        interfaceName: rootInterfaceName
    };
}

function getCsType(excelStruct: ExcelStruct, columnData: ColumnData, jsonStruct: {
    content: string,
    interfaceName: string
} | undefined): string {
    const dataType = columnData.dataType;
    switch (dataType) {
        case DataType.Int:
            return "int";
        case DataType.Float:
            return "float";
        case DataType.String:
            return "string";
        case DataType.Bool:
            return "bool";
        case DataType.Vector2:
            return "Vector2";
        case DataType.Vector2Int:
            return "Vector2Int";
        case DataType.Vector3:
            return "Vector3";
        case DataType.Vector3Int:
            return "Vector3Int";
        case DataType.Vector4:
            return "Vector4";
        case DataType.Vector4Int:
            return "Vector4Int";
        case DataType.ArrayInt:
            return "int[]";
        case DataType.ArrayFloat:
            return "float[]";
        case DataType.ArrayString:
            return "string[]";
        case DataType.ArrayBool:
            return "bool[]";
        case DataType.ArrayVector2:
            return "Vector2[]";
        case DataType.ArrayVector2Int:
            return "Vector2Int[]";
        case DataType.ArrayVector3:
            return "Vector3[]";
        case DataType.ArrayVector3Int:
            return "Vector3Int[]";
        case DataType.ArrayVector4:
            return "Vector4[]";
        case DataType.ArrayVector4Int:
            return "Vector4Int[]";
        case DataType.Json:
            if (jsonStruct) {
                return jsonStruct.interfaceName;
            }
            return "object";
        default:
            return "object";
    }
}
