import { Logger } from "../logger/Logger";
import { ColumnData, ExcelStruct } from "../parser/ExcelParser";
import { DataType } from "../parser/ParserEnum";
import fs from "fs";
import { pathToNormal, toUpperCamelCase } from "../utils/StringUtils";
import { ParseJsonFunc } from "../parser/JsonParser";

const HEAD_ROW_COUNT = 5;     // 表头行数

class JsonKeyValue {
    key: string = "";
    valueType : string = "";
    children: Map<string, JsonKeyValue> = new Map();
}


export function exportCsClass(excelStruct: ExcelStruct, outPath:string) {
    if (excelStruct == null) {
        Logger.error(`exportTsClass error, excelStruct is null`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsClass error, outPath is error: ${outPath}`);
        return;
    }

    const columnDataList = excelStruct.columnDataList;
    if (columnDataList == null || columnDataList.length == 0) {
        Logger.error(`exportTsClass error, columnDataList is null or empty`);
        return;
    }

    const content = generateCsClass(excelStruct);
    let className = excelStruct.configName;
    className = toUpperCamelCase(className);
    outPath = pathToNormal(outPath);
    let newOutPath = outPath.substring(0, outPath.lastIndexOf("/")) + "/" + className + ".cs";
    fs.writeFileSync(newOutPath, content);
}

function generateCsClass(excelStruct: ExcelStruct): string {
    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n`;

    // 类名
    let className = excelStruct.configName;
    // 去除 空格,-,_字符, 并且这些字符后的字母大写
    className = toUpperCamelCase(className);
    className = className.substring(0, 1).toUpperCase() + className.substring(1);
    
    let typeName = className + "Config";
    className += "Class";

    // 命名空间
    let namespace = "FreeParticle.ExcelConfig";
    content += `using System;\n`;
    content += `using System.Collections;\n`;
    content += `using System.Collections.Generic;\n`;
    content += `using Newtonsoft.Json;\n`;
    content += `using UnityEngine;\n\n`;

    content += `namespace ${namespace} {\n\n`;


    const jsonStructMap: Map<string, { content: string, interfaceName: string }> = new Map();
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        if (columnData.dataType == DataType.Json) {
            const jsonStruct = getJsonTypeStruct(excelStruct, columnData);
            jsonStructMap.set(columnData.fieldName, jsonStruct);
        }
    }

    jsonStructMap.forEach((jsonStruct, key) => {
        content += jsonStruct.content + "\n";
    });

    if (excelStruct.subKeyColumn === -1) {
        // 没有子健列
        content += `    public static class ${typeName}\n`;
        content += `    {\n`;
        content += `        public static Dictionary<${getKeyType(excelStruct)}, ${className}> Deserialize(string json) {\n`;
        content += `            var result = JsonConvert.DeserializeObject<Dictionary<${getKeyType(excelStruct)}, ${className}>>(json);\n`;
        content += `            return result;\n`;
        content += `        }\n`;
        content += `    }\n\n`;
    }
    else {
        // 有子健列
        content += `    public static class ${typeName} {\n`;
        content += `        public static Dictionary<${getKeyType(excelStruct)}, Dictionary<${getSubKeyType(excelStruct)}, ${className}>> Deserialize(string json) {\n`;
        content += `            var result = JsonConvert.DeserializeObject<Dictionary<${getKeyType(excelStruct)}, Dictionary<${getSubKeyType(excelStruct)}, ${className}>>>(json);\n`;
        content += `            return result;\n`;
        content += `        }\n`;
        content += `    }\n\n`;
    }

    content += `    [Serializable]\n`;
    content += `    public class ${className} {\n`;
 // 字段
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        content += `        /** ${columnData.commentName} */\n`;
        content += `        [JsonProperty("${columnData.fieldName}")]\n`;
        content += `        public ${getCsType(excelStruct, columnData, jsonStructMap.get(columnData.fieldName))} ${columnData.fieldName} { get; private set; }\n\n`;
    }

    content += `    }\n`;

    content += `}\n`;

    return content;
}

function getKeyType(excelStruct: ExcelStruct): string 
{
    const mainKeyColumnData = excelStruct.columnDataList[excelStruct.mainKeyColumn];
    if (mainKeyColumnData.dataType == DataType.Int) {
        return "int";
    }
    else if (mainKeyColumnData.dataType == DataType.String) {
        return "string";
    }
    return "string"; 
}

function getSubKeyType(excelStruct: ExcelStruct): string
{
    const subKeyColumnData = excelStruct.columnDataList[excelStruct.subKeyColumn];
    if (subKeyColumnData.dataType == DataType.Int) {
        return "int";
    }
    else if (subKeyColumnData.dataType == DataType.String) {
        return "string";
    }
    return "string"; 
}

function getJsonTypeStruct(excelStruct: ExcelStruct, columnData: ColumnData): {
    content: string,
    interfaceName: string
} {
    const jsonStruct: Map<string, JsonKeyValue> = new Map();

    Logger.currentColumnName = columnData.fieldName;
    const rowCount = excelStruct.rowCount;
    const worksheet = excelStruct.sheet!;
    for (let i = HEAD_ROW_COUNT + 1, len = rowCount; i <= len; i++) {
        Logger.currentRow = i;
        const row = worksheet.getRow(i);
        try {
            let text = row.getCell(columnData.column).text;
            if (text == null || text.trim() == "") {
                text = "{}";
            }

            const json = ParseJsonFunc(text);
            if (json == null) {
                Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}`);
                continue;
            }

            const getJsonValueType = function(value : unknown) : string {
                if (typeof value === "string") {
                    return "string";
                }
                else if (typeof value === "number") {
                    return "float"; 
                }
                else if (typeof value === "boolean") {
                    return "bool";
                }
                else if (Array.isArray(value)) {
                    const arrayType = value.length > 0 ? getJsonValueType(value[0]) : "";
                    return arrayType + "[]";
                }
                else if (typeof value === "object") {
                    return "object";
                }
                return "object";
            }

            const parseJson = (table: { [key: string]: unknown }, parent: JsonKeyValue | null = null) => {
                for (const key in table) {
                    const value = table[key];
                    if (typeof value === "object" && !Array.isArray(value)) {
                        let jsonKeyValue = new JsonKeyValue();
                        if (parent) {
                            jsonKeyValue = parent.children.get(key) || new JsonKeyValue();
                        }
                        else {
                            jsonKeyValue = jsonStruct.get(key) || new JsonKeyValue();
                        }
                        jsonKeyValue.key = key;
                        jsonKeyValue.valueType = getJsonValueType(value);
                        if (parent) {
                            if (parent.children.has(key)) {
                                const valueType = parent.children.get(key)!.valueType;
                                if ( valueType == "[]" || valueType == "object") {
                                    parent.children.set(key, jsonKeyValue);
                                }
                            }
                            else {
                                parent.children.set(key, jsonKeyValue);
                            }
                        }
                        else {
                            if (jsonStruct.has(key)) {
                                const valueType = jsonStruct.get(key)!.valueType;
                                if (valueType == "[]" || valueType == "object") {
                                    jsonStruct.set(key, jsonKeyValue);
                                }
                            }
                            else {
                                jsonStruct.set(key, jsonKeyValue);
                            }  
                        }
                        parseJson(value as { [key: string]: unknown }, jsonKeyValue);
                    }
                    else {
                        if (parent) {
                            parent.children.set(key, { key: key, valueType: getJsonValueType(value), children: new Map() });
                        }
                        else {
                            jsonStruct.set(key, { key: key, valueType: getJsonValueType(value), children: new Map() });
                        }
                    }
                }
            }

            parseJson(json);
        }
        catch (error) {
            Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}`);
            Logger.break();
        }
    }

    // 生成类
    // 接口名 = 配表名 + 字段名
    const interfaceName = toUpperCamelCase(excelStruct.configName) + toUpperCamelCase(columnData.fieldName);

    let content = "    [Serializable]\n";
    content += `    public partial class ${interfaceName}` + " {\n";
    // 递归生成类
    const generateInterface = (jsonStruct: Map<string, JsonKeyValue>, tabCount: number) => {
        for (const [key, value] of jsonStruct) {
            let tab = "    ";
            for (let i = 0; i < tabCount; i++) {
                tab += "    ";
            }
            let isJsonTable = false;
            if (value.valueType == "object") {
                content += `${tab}[JsonProperty("${value.key}")]\n`;
                content += `public ${tab}object ${key} {get; private set; }\n`;    // json类型只导出一层结构
                isJsonTable = true;
            }
            else {
                content += `${tab}[JsonProperty("${value.key}")]\n`;
                content += `${tab}public ${value.valueType} ${key} {get; private set; }\n`;
            }

            if (!isJsonTable){
                generateInterface(value.children, tabCount + 1);
            }
            // if (isJsonTable) {
            //     content += `${tab}};\n`;
            // }
        }
    }

    generateInterface(jsonStruct, 1);
    content += "    }\n";

    return {
        content: content,
        interfaceName: interfaceName
    };
}

function getCsType(excelStruct: ExcelStruct, columnData: ColumnData, jsonStruct: {
    content: string,
    interfaceName: string
} | undefined): string {
    const dataType = columnData.dataType;
    switch (dataType) {
        case DataType.Int:
            return "int";
        case DataType.Float:
            return "float";
        case DataType.String:
            return "string";
        case DataType.Bool:
            return "bool";
        case DataType.Vector2:
            return "Vector2";
        case DataType.Vector2Int:
            return "Vector2Int";
        case DataType.Vector3:
            return "Vector3";
        case DataType.Vector3Int:
            return "Vector3Int";
        case DataType.Vector4:
            return "Vector4";
        case DataType.Vector4Int:
            return "Vector4Int";
        case DataType.ArrayInt:
            return "int[]";
        case DataType.ArrayFloat:
            return "float[]";
        case DataType.ArrayString:
            return "string[]";
        case DataType.ArrayBool:
            return "bool[]";
        case DataType.ArrayVector2:
            return "Vector2[]";
        case DataType.ArrayVector2Int:
            return "Vector2Int[]";
        case DataType.ArrayVector3:
            return "Vector3[]";
        case DataType.ArrayVector3Int:
            return "Vector3Int[]";
        case DataType.ArrayVector4:
            return "Vector4[]";
        case DataType.ArrayVector4Int:
            return "Vector4Int[]";
        case DataType.Json:
            if (jsonStruct) {
                return jsonStruct.interfaceName;
            }
            return "object";
        default:
            return "object";
    }
}
