import { Logger } from "../logger/Logger";
import fs from "fs";
import { toUpperCamelCase } from "../utils/StringUtils";

export function exportCsConfigNameList(pathArray: string[], outPath: string) {
    if (pathArray == null || pathArray.length == 0) {
        Logger.error(`exportTsConfigEnum error, pathArray is null or empty`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsConfigEnum error, outPath is error: ${outPath}`);
        return;
    }

    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n\n`;
    content += `using System;\n`;
    content += `using System.Collections.Generic;\n`;
    content += `using Newtonsoft.Json;\n`;

    content += `namespace FreeParticle.ExcelConfig {\n`;
    content += `    public static class ExcelName {\n`;
    content += `        public readonly static string[] ExcelNameList = new string[] {\n`;
    for (let i = 0, len = pathArray.length; i < len; i++) {
        const path = pathArray[i];
        const configName = path.substring(path.lastIndexOf("/") + 1, path.lastIndexOf("."));
        content += `            "${configName}",\n`;
    }
    content += `        };\n`;

    content += `\n`;
    content += `        public readonly static Dictionary<string, Func<string, object>> ExcelParserMap\n`;
    content += `            = new Dictionary<string, Func<string, object>>() {\n`;
    for (let i = 0, len = pathArray.length; i < len; i++) {
        const path = pathArray[i];
        const configName = path.substring(path.lastIndexOf("/") + 1, path.lastIndexOf("."));
        const className = toUpperCamelCase(configName);
        content += `            { "${configName}", json => ${className}Config.Deserialize(json) },\n`;
    }
    content += `        };\n`;

    // 导出每个配置的资源名称
    for (let i = 0, len = pathArray.length; i < len; i++) {
        const path = pathArray[i];
        const configName = path.substring(path.lastIndexOf("/") + 1, path.lastIndexOf("."));
        const className = toUpperCamelCase(configName);
        content += `        public const string ${className} = "${configName}";\n`;
    }
    content += `\n`;

    content += `    }\n`;
    content += `}\n`;

    fs.writeFileSync(outPath, content);
}
