import { Logger } from "../logger/Logger";
import { ExcelStruct } from "../parser/ExcelParser";
import { DataType } from "../parser/ParserEnum";
import fs from "fs";

/**
 * 导出.d.ts文件, 用于编写TypeScript的智能提示
 */
export function exportTsClass(excelStruct: ExcelStruct, outPath: string) {
    if (excelStruct == null) {
        Logger.error(`exportTsClass error, excelStruct is null`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsClass error, outPath is error: ${outPath}`);
        return;
    }

    const columnDataList = excelStruct.columnDataList;
    if (columnDataList == null || columnDataList.length == 0) {
        Logger.error(`exportTsClass error, columnDataList is null or empty`);
        return;
    }

    const content = generateTsClass(excelStruct);
    fs.writeFileSync(outPath, content);
}

/**
 * 生成.d.ts文件内容
 * @param excelStruct Excel结构
 */
function generateTsClass(excelStruct: ExcelStruct): string {
    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n\n`;

    // 类名
    let className = excelStruct.configName;
    // 去除 空格,-,_字符, 并且这些字符后的字母大写
    className = className.replace(/[\s\-_](\w)/g, (all, letter) => letter.toUpperCase());
    className = className.substring(0, 1).toUpperCase() + className.substring(1);

    let typeName = className + "Config";
    className += "Class";

    if (excelStruct.subKeyColumn === -1) {
        content += `export type ${typeName} = { [key: string]: ${className} };\n\n`;
    }
    else {
        // 有子键
        content += `export type ${typeName} = { [key: string]: { [key: string]: ${className} } };\n\n`;
    }

    content += `export class ${className} 
{\n`;

    // 字段
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        content += `    /** ${columnData.commentName} */\n`;
        content += `    ${columnData.fieldName}: ${getTsType(columnData.dataType)};\n\n`;
    }

    content += `}\n`;

    return content;
}

/**
 * 获取TypeScript类型
 * @param dataType 数据类型
 */
function getTsType(dataType: DataType): string {
    switch (dataType) {
        case DataType.Int:
        case DataType.Float:
            return "number";
        case DataType.String:
            return "string";
        case DataType.Bool:
            return "boolean";
        case DataType.Vector2:
            return "{ x: number, y: number }";
        case DataType.Vector3:
            return "{ x: number, y: number, z: number }";
        case DataType.Vector4:
            return "{ x: number, y: number, z: number, w: number }";
        case DataType.ArrayInt:
            return "number[]";
        case DataType.ArrayFloat:
            return "number[]";
        case DataType.ArrayString:
            return "string[]";
        case DataType.ArrayBool:
            return "boolean[]";
        case DataType.ArrayVector2:
            return "{ x: number, y: number }[]";
        case DataType.ArrayVector3:
            return "{ x: number, y: number, z: number }[]";
        case DataType.ArrayVector4:
            return "{ x: number, y: number, z: number, w: number }[]";
        default:
            return "any";
    }
}


