import { Logger } from "../logger/Logger";
import { ColumnData, ExcelStruct } from "../parser/ExcelParser";
import { DataType } from "../parser/ParserEnum";
import fs from "fs";
import { pathToNormal, toUpperCamelCase } from "../utils/StringUtils";

const HEAD_ROW_COUNT = 5;     // 表头行数

class JsonKeyValue {
    key: string = "";
    valueType : string = "";
    children: Map<string, JsonKeyValue> = new Map();
}

/**
 * 导出.d.ts文件, 用于编写TypeScript的智能提示
 */
export function exportTsClass(excelStruct: ExcelStruct, outPath: string) {
    if (excelStruct == null) {
        Logger.error(`exportTsClass error, excelStruct is null`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsClass error, outPath is error: ${outPath}`);
        return;
    }

    const columnDataList = excelStruct.columnDataList;
    if (columnDataList == null || columnDataList.length == 0) {
        Logger.error(`exportTsClass error, columnDataList is null or empty`);
        return;
    }

    const content = generateTsClass(excelStruct);
    let className = excelStruct.configName;
    className = toUpperCamelCase(className);
    outPath = pathToNormal(outPath);
    let newOutPath = outPath.substring(0, outPath.lastIndexOf("/")) + "/" + className + ".d.ts";
    fs.writeFileSync(newOutPath, content);
}

/**
 * 生成.d.ts文件内容
 * @param excelStruct Excel结构
 */
function generateTsClass(excelStruct: ExcelStruct): string {
    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n\n`;

    // 类名
    let className = excelStruct.configName;
    // 去除 空格,-,_字符, 并且这些字符后的字母大写
    className = toUpperCamelCase(className);
    className = className.substring(0, 1).toUpperCase() + className.substring(1);

    let typeName = className + "Config";
    className += "Class";

    content += `import { IExcelConfig } from "./IExcelConfig";\n\n`;

    const jsonStructMap: Map<string, { content: string, interfaceName: string }> = new Map();
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        if (columnData.dataType == DataType.Json) {
            const jsonStruct = getJsonTypeStruct(excelStruct, columnData);
            jsonStructMap.set(columnData.fieldName, jsonStruct);
        }
    }

    jsonStructMap.forEach((jsonStruct, key) => {
        content += jsonStruct.content + "\n";
    });

    if (excelStruct.subKeyColumn === -1) {
        content += `export type ${typeName} = { [key: string]: ${className} };\n\n`;
    }
    else {
        // 有子键
        content += `export type ${typeName} = { [key: string]: { [key: string]: ${className} } };\n\n`;
    }

    content += `export class ${className} implements IExcelConfig
{\n`;

    // 字段
    for (let i = 0, len = excelStruct.columnDataList.length; i < len; i++) {
        const columnData = excelStruct.columnDataList[i];
        content += `    /** ${columnData.commentName} */\n`;
        content += `    ${columnData.fieldName}: ${getTsType(excelStruct, columnData, jsonStructMap.get(columnData.fieldName))};\n\n`;
    }

    content += `}\n`;

    return content;
}

function getJsonTypeStruct(excelStruct: ExcelStruct, columnData: ColumnData): {
    content: string,
    interfaceName: string
} {
    const jsonStruct: Map<string, JsonKeyValue> = new Map();

    Logger.currentColumnName = columnData.fieldName;
    const rowCount = excelStruct.rowCount;
    const worksheet = excelStruct.sheet!;
    for (let i = HEAD_ROW_COUNT + 1, len = rowCount; i <= len; i++) {
        Logger.currentRow = i;
        const row = worksheet.getRow(i);
        try {
            let text = row.getCell(columnData.column).text;
            if (text == null || text.trim() == "") {
                text = "{}";
            }

            const json = JSON.parse(text);
            if (json == null) {
                Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}`);
                continue;
            }

            const getJsonValueType = function(value : unknown) : string {
                if (typeof value === "string") {
                    return "string";
                }
                else if (typeof value === "number") {
                    return "number";
                }
                else if (typeof value === "boolean") {
                    return "boolean";
                }
                else if (Array.isArray(value)) {
                    const arrayType = value.length > 0 ? getJsonValueType(value[0]) : "";
                    return arrayType + "[]";
                }
                else if (typeof value === "object") {
                    return "object";
                }
                return "unknown";
            }

            const parseJson = (table: { [key: string]: unknown }, parent: JsonKeyValue | null = null) => {
                for (const key in table) {
                    const value = table[key];
                    if (typeof value === "object" && !Array.isArray(value)) {
                        const jsonKeyValue = new JsonKeyValue();
                        jsonKeyValue.key = key;
                        jsonKeyValue.children = new Map();
                        jsonKeyValue.valueType = getJsonValueType(value);
                        if (parent) {
                            if (parent.children.has(key)) {
                                const valueType = parent.children.get(key)!.valueType;
                                if (valueType == "unknown" || valueType == "[]" || valueType == "object") {
                                    parent.children.set(key, jsonKeyValue);
                                }
                            }
                            else {
                                parent.children.set(key, jsonKeyValue);
                            }
                        }
                        else {
                            if (jsonStruct.has(key)) {
                                const valueType = jsonStruct.get(key)!.valueType;
                                if (valueType == "unknown" || valueType == "[]" || valueType == "object") {
                                    jsonStruct.set(key, jsonKeyValue);
                                }
                            }
                            else {
                                jsonStruct.set(key, jsonKeyValue);
                            }  
                        }
                        parseJson(value as { [key: string]: unknown }, jsonKeyValue);
                    }
                    else {
                        if (parent) {
                            parent.children.set(key, { key: key, valueType: getJsonValueType(value), children: new Map() });
                        }
                        else {
                            jsonStruct.set(key, { key: key, valueType: getJsonValueType(value), children: new Map() });
                        }
                    }
                }
            }

            parseJson(json);
        }
        catch (error) {
            Logger.error(`解析Json错误, row: ${i}, column: ${columnData.column}`);
        }
    }

    // 生成接口类型 export interface 接口名 {  }
    // 接口名 = 配表名 + 字段名
    const interfaceName = toUpperCamelCase(excelStruct.configName) + toUpperCamelCase(columnData.fieldName);
    let content = `export interface ${interfaceName}` + " {\n";

    // 递归生成接口类型
    const generateInterface = (jsonStruct: Map<string, JsonKeyValue>, tabCount: number) => {
        for (const [key, value] of jsonStruct) {
            let tab = "";
            for (let i = 0; i < tabCount; i++) {
                tab += "    ";
            }
            let isJsonTable = false;
            if (value.valueType == "object") {
                content += `${tab}${key}: {\n`;
                isJsonTable = true;
            }
            else {
                content += `${tab}${key}: ${value.valueType};\n`;
            }
            generateInterface(value.children, tabCount + 1);
            if (isJsonTable) {
                content += `${tab}};\n`;
            }
        }
    }

    generateInterface(jsonStruct, 1);
    content += "}\n";

    return {
        content: content,
        interfaceName: interfaceName
    };
}

/**
 * 获取TypeScript类型
 */
function getTsType(excelStruct: ExcelStruct, columnData: ColumnData, jsonStruct: {
    content: string,
    interfaceName: string
} | undefined): string {
    const dataType = columnData.dataType;
    switch (dataType) {
        case DataType.Int:
        case DataType.Float:
            return "number";
        case DataType.String:
            return "string";
        case DataType.Bool:
            return "boolean";
        case DataType.Vector2:
        case DataType.Vector2Int:
            return "{ x: number, y: number }";
        case DataType.Vector3:
        case DataType.Vector3Int:
            return "{ x: number, y: number, z: number }";
        case DataType.Vector4:
        case DataType.Vector4Int:
            return "{ x: number, y: number, z: number, w: number }";
        case DataType.ArrayInt:
            return "number[]";
        case DataType.ArrayFloat:
            return "number[]";
        case DataType.ArrayString:
            return "string[]";
        case DataType.ArrayBool:
            return "boolean[]";
        case DataType.ArrayVector2:
        case DataType.ArrayVector2Int:
            return "{ x: number, y: number }[]";
        case DataType.ArrayVector3:
        case DataType.ArrayVector3Int:
            return "{ x: number, y: number, z: number }[]";
        case DataType.ArrayVector4:
        case DataType.ArrayVector4Int:
            return "{ x: number, y: number, z: number, w: number }[]";
        case DataType.Json:
            if (jsonStruct) {
                return jsonStruct.interfaceName;
            }
            return "{ [key: string]: unknown }";
        default:
            return "any";
    }
}


