import { Logger } from "../logger/Logger";
import fs from "fs";
import { toUpperCamelCase } from "../utils/StringUtils";

export function exportTsConfigEnum(pathArray: string[], outPath: string) {
    if (pathArray == null || pathArray.length == 0) {
        Logger.error(`exportTsConfigEnum error, pathArray is null or empty`);
        return;
    }

    if (outPath == null || outPath == "") {
        Logger.error(`exportTsConfigEnum error, outPath is error: ${outPath}`);
        return;
    }

    let content = `// This file is auto generated by ExcelExportTools, do not modify it.\n\n`;
    content += `export enum ExcelName {\n`;

    for (let i = 0, len = pathArray.length; i < len; i++) {
        const path = pathArray[i];
        const configName = path.substring(path.lastIndexOf("/") + 1, path.lastIndexOf("."));
        const configNameUpper = toUpperCamelCase(configName);
        content += `    ${configNameUpper} = "${configName}",\n`;
    }

    content += `}\n`;

    fs.writeFileSync(outPath, content);
    
}