// This file is auto generated by ExcelExportTools, do not modify it.

export enum ExcelName {
    UnionDonate = "union_donate",
    UnionDonateReward = "union_donate__reward",
    UnionFlagIcon = "union_flag_icon",
    UnionMiracleDailyBox = "union_miracle_daily_box",
    UnionMiracleSpReward = "union_miracle_sp_reward",
    UnionOfficial = "union_official",
}
