// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionDonateConfig = { [key: string]: UnionDonateClass };

export class UnionDonateClass implements IExcelConfig
{
    /** 捐献类型 */
    id: number;

    /** 消耗货币值 */
    cost: { x: number, y: number, z: number };

    /** 返回恩惠值 */
    return_value: number;

    /** 每日捐献次数 */
    daily_count: number;

}
