// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionFlagIconConfig = { [key: string]: UnionFlagIconClass };

export class UnionFlagIconClass implements IExcelConfig
{
    /** 图标id */
    id: number;

    /** 图标种类 */
    icon_kind: number;

    /** 图标名称 */
    icon_name: string;

}
