// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionOfficialConfig = { [key: string]: UnionOfficialClass };

export class UnionOfficialClass implements IExcelConfig
{
    /** 联盟阶级 */
    level: number;

    /** 阶级人数 */
    max: number;

    /** 成员类型
1.盟主;4.官员;5.成员; */
    name: string;

    /** 退出联盟 */
    alliance_exit: number;

    /** 提高/降低成员等级 */
    alliance_change_level: number;

    /** 转让盟主 */
    alliance_change_leader: number;

    /** 入盟邀请 */
    alliance_invitation: number;

    /** 入盟审核 */
    alliance_audit: number;

    /** 成员移除 */
    alliance_remove: number;

    /** 编辑联盟资料 */
    alliance_edit_info: number;

    /** 解散联盟 */
    alliance_dissolve: number;

    /** 管理集结部队 */
    alliance_edit_assemble: number;

    /** 全盟邮件 */
    sent_all_allies_mail: number;

    /** 遣返（奇观）成员部队 */
    kick_march: number;

}
