// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionDonateRewardConfig = { [key: string]: UnionDonateRewardClass };

export class UnionDonateRewardClass implements IExcelConfig
{
    /** id */
    id: number;

    /** 黄金树等级 */
    level: number;

    /** 升级需要经验 */
    upgrade_exp: number;

    /** 5个箱子需要捐献值 */
    draw_need_count: number[];

    /** 5个箱子掉落 */
    draw_reward: number[];

    /** 箱子1外显 */
    draw_show_box_1: { x: number, y: number, z: number }[];

    /** 箱子2外显 */
    draw_show_box_2: { x: number, y: number, z: number }[];

    /** 箱子3外显 */
    draw_show_box_3: { x: number, y: number, z: number }[];

    /** 箱子4外显 */
    draw_show_box_4: { x: number, y: number, z: number }[];

    /** 箱子5外显 */
    draw_show_box_5: { x: number, y: number, z: number }[];

}
