// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionMiracleSpRewardConfig = { [key: string]: { [key: string]: UnionMiracleSpRewardClass } };

export class UnionMiracleSpRewardClass implements IExcelConfig
{
    /** 赛季id */
    id: number;

    /** 奖励等级 */
    sp_num: number;

    /** 需要混沌值 */
    chaos_value: number;

    /** 对应赛季奖励 */
    reward: { x: number, y: number, z: number }[];

}
