// This file is auto generated by ExcelExportTools, do not modify it.

import { IExcelConfig } from "./IExcelConfig";

export type UnionMiracleDailyBoxConfig = { [key: string]: UnionMiracleDailyBoxClass };

export class UnionMiracleDailyBoxClass implements IExcelConfig
{
    /** id */
    id: number;

    /** 奖励等级 */
    reward_level: number;

    /** 需要混沌值 */
    chaos_value: number;

    /** 对应每日奖励 */
    reward: { x: number, y: number, z: number }[];

}
